version: '3.3'

services:
  rabbitmq:
    image: rabbitmq:3-management
    container_name: rabbitmq
    volumes:
      - vol:/var/lib/rabbitmq
      - log:/var/log/rabbitmq
    networks:
      - net
    ports:
      - "${SERVER_PORT}:5672"
      - "${MANAGEMENT_PORT}:15672"            
    environment:
      - RABBITMQ_DEFAULT_USER=${DEFAULT_USERNAME}
      - RABBITMQ_DEFAULT_PASS=${DEFAULT_PASSWORD}

volumes:
  vol:
    driver: local
  log:
    driver: local

networks:
  net:
    driver: bridge