version: '3.3'

services:
  rabbitmq:
    image: rabbitmq:3-management
    container_name: rabbitmq
    volumes:
      - rabbitmq-vol:/var/lib/rabbitmq
      - rabbitmq-log:/var/log/rabbitmq
      - ./conf/:/etc/rabbitmq/
    networks:
      - rabbitmq-net
    ports:
      - "5672:5672"
      - "15672:15672"            
    environment:
      - RABBITMQ_DEFAULT_USER=root
      - RABBITMQ_DEFAULT_PASS=pass

volumes:
  rabbitmq-vol:
    driver: local
  rabbitmq-log:
    driver: local

networks:
  rabbitmq-net:
    driver: bridge