version: '3.3'

services:
  rabbitmq:
    image: rabbitmq:3-management
    container_name: rabbitmq
    volumes:
      - rabbitmq-vol:/var/lib/rabbitmq
      - rabbitmq-log:/var/log/rabbitmq
      - ./conf/:/etc/rabbitmq/
    networks:
      - rabbitmq-net
    ports:
      - "${SERVER_PORT}:5672"
      - "${MANAGEMENT_PORT}:15672"            
    environment:
      - RABBITMQ_DEFAULT_USER=${DEFAULT_USERNAME}
      - RABBITMQ_DEFAULT_PASS=${DEFAULT_PASSWORD}

volumes:
  rabbitmq-vol:
    driver: local
  rabbitmq-log:
    driver: local

networks:
  rabbitmq-net:
    driver: bridge